export { default as Home } from './Home'
export { default as Admin } from './Admin'
export { default as Contact } from './Contact'
export { default as OrderHistory } from './OrderHistory'
export { default as Cart } from './Cart'
