export { default as Home } from './Home'
export { default as Admin } from './Admin'
export { default as Contact } from './Contact'
export { default as OrderHistory } from './OrderHistory'
export { default as Cart } from './Cart'
export { default as Login } from './auth/Login'
export { default as Register } from './auth/Register'
export { default as Reset } from './auth/Reset'
