const CREATE_USER_WITH_EMAIL_AND_PASSWORD_REQUEST =
  'CREATE_USER_WITH_EMAIL_AND_PASSWORD_REQUEST'
const CREATE_USER_WITH_EMAIL_AND_PASSWORD_SUCCESS =
  'CREATE_USER_WITH_EMAIL_AND_PASSWORD_SUCCESS'
const CREATE_USER_WITH_EMAIL_AND_PASSWORD_FAILED =
  'CREATE_USER_WITH_EMAIL_AND_PASSWORD_FAILED'

const SIGN_IN_WITH_EMAIL_AND_PASSWORD_REQUEST =
  'SIGN_IN_WITH_EMAIL_AND_PASSWORD_REQUEST'
const SIGN_IN_WITH_EMAIL_AND_PASSWORD_SUCCESS =
  'SIGN_IN_WITH_EMAIL_AND_PASSWORD_SUCCESS'
const SIGN_IN_WITH_EMAIL_AND_PASSWORD_FAILED =
  'SIGN_IN_WITH_EMAIL_AND_PASSWORD_FAILED'

const SIGN_OUT = 'SIGN_OUT'
const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS'
const SIGN_OUT_FAILED = 'SIGN_OUT_FAILED'

const SIGN_IN_WITH_GOOGLE_REQUEST = 'SIGN_IN_WITH_GOOGLE_REQUEST'
const SIGN_IN_WITH_GOOGLE_SUCCESS = 'SIGN_IN_WITH_GOOGLE_SUCCESS'
const SIGN_IN_WITH_GOOGLE_FAILED = 'SIGN_IN_WITH_GOOGLE_FAILED'

const userTypes = {
  CREATE_USER_WITH_EMAIL_AND_PASSWORD_REQUEST,
  CREATE_USER_WITH_EMAIL_AND_PASSWORD_SUCCESS,
  CREATE_USER_WITH_EMAIL_AND_PASSWORD_FAILED,
  SIGN_IN_WITH_EMAIL_AND_PASSWORD_REQUEST,
  SIGN_IN_WITH_EMAIL_AND_PASSWORD_SUCCESS,
  SIGN_IN_WITH_EMAIL_AND_PASSWORD_FAILED,
  SIGN_OUT,
  SIGN_OUT_SUCCESS,
  SIGN_OUT_FAILED,
  SIGN_IN_WITH_GOOGLE_REQUEST,
  SIGN_IN_WITH_GOOGLE_SUCCESS,
  SIGN_IN_WITH_GOOGLE_FAILED,
}

export default userTypes
